### ISSUE TITLE
0.2.0-test12无法启动插件

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/QQWifeLottery#3]
2023-12-09 01:07:49 E/来个老婆48成员版: java.lang.RuntimeException: Error initializing logs table.
java.lang.RuntimeException: Error initializing logs table.
        at wifeLottery48-0.2.0-test12.mirai2.jar//net.lawaxi.lottery.manager.database.initDatabase(database.java:98)
        at wifeLottery48-0.2.0-test12.mirai2.jar//net.lawaxi.lottery.manager.database.<init>(database.java:22)
        at wifeLottery48-0.2.0-test12.mirai2.jar//net.lawaxi.lottery.manager.config.<init>(config.java:86)
        at wifeLottery48-0.2.0-test12.mirai2.jar//net.lawaxi.lottery.WifeLottery.onEnable(WifeLottery.java:38)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:244)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:393)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:40)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:54)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:193)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:360)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "AUTO_INCREMENT": syntax error)
        at wifeLottery48-0.2.0-test12.mirai2.jar[private]//org.sqlite.core.DB.newSQLException(DB.java:1012)
        at wifeLottery48-0.2.0-test12.mirai2.jar[private]//org.sqlite.core.DB.newSQLException(DB.java:1024)
        at wifeLottery48-0.2.0-test12.mirai2.jar[private]//org.sqlite.core.DB.throwex(DB.java:989)
        at wifeLottery48-0.2.0-test12.mirai2.jar[private]//org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at wifeLottery48-0.2.0-test12.mirai2.jar[private]//org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
        at wifeLottery48-0.2.0-test12.mirai2.jar[private]//org.sqlite.core.DB.prepare(DB.java:257)
        at wifeLottery48-0.2.0-test12.mirai2.jar[private]//org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:45)
        at wifeLottery48-0.2.0-test12.mirai2.jar//net.lawaxi.lottery.manager.database.initDatabase(database.java:95)
        ... 15 more

**Comment by Lawaxi** [comment]
刚刚发布的0.2.1解决了这两个问题
