### ISSUE TITLE
数据迁移报错

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/QQWifeLottery#4]
2023-12-09 03:05:56 E/console: cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:396)
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.JSONParser.parseTo(JSONParser.java:51)
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.ObjectMapper.mapFromTokener(ObjectMapper.java:231)
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.ObjectMapper.mapFromStr(ObjectMapper.java:207)
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.ObjectMapper.map(ObjectMapper.java:98)
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.JSONObject.<init>(JSONObject.java:211)
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.JSONObject.<init>(JSONObject.java:188)
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.JSONObject.<init>(JSONObject.java:143)
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.JSONObject.<init>(JSONObject.java:126)
        at wifeLottery48-0.2.0-test6.mirai2.jar[private]//cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:90)
        at wifeLottery48-0.2.0-test6.mirai2.jar//net.lawaxi.lottery.manager.MyCommands.migrate(MyCommands.java:57)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1$invokeSuspend$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Lawaxi** [comment]
刚刚发布的0.2.1解决了这两个问题

**Comment by onlyzqy** [comment]
> /wife48 migrate
2023-12-15 23:47:35 I/stdout: [2023-12-15 23:47:35] [DEBUG] cn.hutool.setting.SettingLoader: Load setting file [D:\Mirai-2.15.0\config\net.lawaxi.wifeOttery48\config.setting]
2023-12-15 23:47:35 E/console: java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.Long; ([Ljava.lang.Object; and [Ljava.lang.Long; are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.Long; ([Ljava.lang.Object; and [Ljava.lang.Long; are in module java.base of loader 'bootstrap')
        at wifeLottery48-0.2.1.mirai2.jar//net.lawaxi.lottery.manager.MyCommands.migrate(MyCommands.java:64)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1$invokeSuspend$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
